---
title: Pesantren Kampung Santri
timezone: Asia/Jakarta
collections:
  agendas:
    title: Agendas
    output: true
    alt-name: Agenda Kegiatan Harian Santri
  aktivitas:
    title: Aktivitas
    output: true
    alt-name: Galeri KS
  cultures:
    title: Cultures
    output: true
    alt-name: Budaya
  fasilitas:
    title: Fasilitas
    output: true
  visits:
    title: Visits
    output: true
    alt-name: Kunjungan Tokoh
  misi:
    title: Misi
    output: true
  psb:
    title: PSB
    output: true
  posts:
    title: Posts
    output: true
  schools:
    title: Schools
    output: true
  teachers:
    title: Teachers
    output: true
    alt-name: Asatidzah
  testimonies:
    title: Testimonies
    output: true
    alt-name: Kata Mereka
  uploads:
    title: Uploads
    output: true
  values:
    title: Values
    output: true
  guests:
    title: Guests
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    bgimg:
- scope:
    path: ''
    type: fasilitas
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: default
    permalink: "/fasilitas/:title/"
- scope:
    path: ''
    type: teachers
  values:
    jabatan:
    img:
    img-alt:
    layout: post
    permalink: "/teachers/:title/"
permalink: pretty
tagline: "Pesantren Pilihan Keluarga"
logo:
  url: "/img/logo.png"
  alt: Pesantren Kampung Santri
favicon:
  url: "/uploads/favicon.png"
contact:
  name: Layanan Kampung Santri
  username: pesantrenkampungsantri
  phone: 62811-244-5575
  message: "Assalamu 'alaykum, Kampung Santri. Mohon ijin bertanya."
narrative:
  home:
    title: Pesantren Kampung Santri
    bgimg: "/uploads/beranda-header.jpg"
    comment: "Bekali Ananda dengan pendidikan terbaik untuk masa depan gemilang.<br/><br/>#AyoKeKampungSantri<br/><br/>Pesantren Kampung Santri hadir untuk menjadi pilihan pendidikan Islam sesuai manhaj Ahlussunnah wal Jama'ah. Dengan kurikulum yang khas, Pesantren Kampung Santri selalu berupaya mewujudkan lulusan yang bertauhid, berkarakter, berwawasan global, dan beramal shalih sesuai tuntunan Al-Qur'an dan Sunnah."
    cta-btn: Ahlan wa Sahlan
    cta-url: selayang
  selayang:
    title: Selayang Pandang
    comment: dari Pengasuh Pesantren
  visi:
    title: Visi
    icon: ussunnah
    comment: "Menjadi pesantren pilihan yang unggul dalam mendidik generasi yang bertauhid, berkarakter, berwawasan global, dan beramal shalih sesuai tuntunan Al-Qur'an dan Sunnah."
  misi:
    title: Misi
    comment: 
  asatidzah:
    title: Kenali Lebih Dekat
    comment: Para ustadz dan ustadzah Kampung Santri, bersama Ayah-Bunda, menghadirkan pendidikan dan pengasuhan yang insyaAllah melahirkan kader al-madrasah al-ula.
  testimony:
    title: Kata Hati
    comment: ...para santri, wali santri, dan alumni Pesantren Kampung Santri.
  agenda:
    title: Agenda Harian Santri
    comment: Setiap detik di sepanjang hidup seorang Muslim hendaknya diisi dengan ibadah kepada Allah 'Azza wa Jalla semata.
  fasilitas:
    title: Fasilitas
    comment: Nikmatnya menuntut ilmu syar'i. Serasa di rumah sendiri.
  kegiatan:
    title: Kegiatan
    comment: Karena setiap detik yang berlalu, akan dipertanggungjawabkan.
  budaya:
    title: Budaya Kampung Santri
    comment: 
  nilai:
    title: Prinsip Pelayanan
    comment:
  apresiasi:
    title: Kajian
    comment: Asatidz bersama Pesantren Kampung Santri
  edu:
    title: Pesantren Kampung Santri
    comment: Mendidik santri tak ubahnya mendidik anak sendiri. Segalanya, kita upayakan yang terbaik. Karena segalanya, akan dipertanggungjawabkan.
    bgimg: "/uploads/pendidikan-header.jpg"
  jenjang:
    title: Jenjang Pendidikan
    comment: Tuntutlah ilmu dari buaian hingga ke liang lahad.
  psb:
    title: Penerimaan Santri Baru
    comment: Bila berminat, sila kuatkan niat dan ikuti tahapannya dengan khidmat.
  kunjungan:
    title: Kunjungan
    comment:
social:
  - title: facebook
    url: https://fb.me/pesantrenkampungsantri
  - title: instagram
    url: https://instagram.com/pesantrenkampungsantri
  - title: youtube
    url: https://youtube.com/pesantrenkampungsantri
  - title: telegram
    url: https://t.me/pesantrenkampungsantri
  - title: link
    url: https://linktr.ee/pesantrenkampungsantri
  - title: whatsapp
    url: https://wa.me/+628112445575
plugins:
  - jekyll-paginate
paginate: 6
paginate_path: "/warta/page:num/"