---
title: Pesantren Kampung Santri
timezone: Asia/Jakarta
collections:
  agendas:
    title: Agendas
    output: true
    alt-name: Agenda Kegiatan Harian Santri
  aktivitas:
    title: Aktivitas
    output: true
    alt-name: Galeri KS
  cultures:
    title: Cultures
    output: true
    alt-name: Budaya
  fasilitas:
    title: Fasilitas
    output: true
  visits:
    title: Visits
    output: true
    alt-name: Kunjungan Tokoh
  misi:
    title: Misi
    output: true
  psb:
    title: PSB
    output: true
  posts:
    title: Posts
    output: true
  schools:
    title: Schools
    output: true
  teachers:
    title: Teachers
    output: true
    alt-name: Asatidzah
  testimonies:
    title: Testimonies
    output: true
    alt-name: Kata Mereka
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    bgimg:
- scope:
    path: ''
    type: fasilitas
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: default
    permalink: "/fasilitas/:title/"
- scope:
    path: ''
    type: teachers
  values:
    jabatan:
    img:
    img-alt:
    layout: post
    permalink: "/teachers/:title/"
permalink: pretty
tagline: Beradab. Berilmu. Berdikari.
logo:
  url: "/img/logo.png"
  alt: Pesantren Kampung Santri
favicon:
  url: "/uploads/favicon.png"
contact:
  name: Admin Kampung Santri
  username: pesantrenkampungsantri
  phone: +628112445575
narrative:
  home:
    title: Pesantren Kampung Santri
    bgimg: "/uploads/beranda-header.jpg"
    comment: Putri-putri kita adalah calon pendidik dan pengasuh utama generasi kaum muslimin di masa depan. Pastikan mereka tumbuh dalam indahnya hidayah, nikmatnya ibadah, dan tenteramnya Sunnah.
    cta-btn: Ahlan wa Sahlan
    cta-url: selayang
  selayang:
    title: Selayang Pandang
    comment: dari Pengasuh Pesantren
  visi:
    title: Visi
    icon: ussunnah
    comment: Menjadi pesantren pilihan yang unggul dalam mendidik generasi yang beradab, berilmu, dan berdikari.
  misi:
    title: Misi
    comment: 
  asatidzah:
    title: Asatidzah
    comment: Bersama Aba dan Umma, menghadirkan pendidikan dan pengasuhan yang insyaAllah melahirkan kader al-madrasah al-ula.
  testimony:
    title: Kata Mereka
    comment: ...tentang Pesantren Kampung Santri.
  agenda:
    title: Agenda Harian Santri
    comment: Setiap detik di sepanjang hidup seorang Muslim hendaknya diisi dengan ibadah kepada Allah 'Azza wa Jalla semata.
  fasilitas:
    title: Fasilitas
    comment: Nikmatnya menuntut ilmu syar'i. Serasa di rumah sendiri.
  kegiatan:
    title: Kegiatan
    comment: Karena setiap detik yang berlalu, akan dipertanggungjawabkan.
  budaya:
    title: Budaya
    comment: 
  apresiasi:
    title: Apresiasi
    comment: Kampung Santri bersama Asatidz
  edu:
    title: Pendidikan di Kampung Santri
    comment: Mendidik santri tak ubahnya mendidik anak sendiri. Segalanya, kita upayakan yang terbaik. Karena segalanya, akan dipertanggungjawabkan.
    bgimg: "/uploads/pendidikan-header.jpg"
  jenjang:
    title: Jenjang Pendidikan
    comment: Tuntutlah ilmu dari buaian hingga ke liang lahad.
  psb:
    title: Penerimaan Santri Baru
    comment: Bila berminat, sila kuatkan niat dan ikuti tahapannya dengan khidmat.
social:
  - title: facebook
    url: https://fb.me/pesantrenkampungsantri
  - title: instagram
    url: https://instagram.com/pesantrenkampungsantri
  - title: youtube
    url: https://youtube.com/pesantrenkampungsantri
  - title: telegram
    url: https://t.me/pesantrenkampungsantri
  - title: link
    url: https://linktr.ee/pesantrenkampungsantri
  - title: whatsapp
    url: https://wa.me/+628112445575