---
title: Pesantren Kampung Santri
timezone: Asia/Jakarta
collections:
  fasilitas:
    title: Fasilitas
    output: true
  kunjungan-tokoh:
    title: Kunjungan Tokoh
    output: true
  psb:
    title: PSB
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: fasilitas
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: default
    permalink: "/fasilitas/:title/"
permalink: pretty
tagline: Beradab. Berilmu. Berdikari.
logo:
  url: "/img/logo.png"
  alt: Pesantren Kampung Santri
favicon:
  url: "/uploads/favicon.png"
narrative:
  fasilitas:
    title: Fasilitas
    comment: Nikmatnya menuntut ilmu syar'i. Serasa di rumah sendiri.
  kegiatan:
    title: Kegiatan
    comment: Karena setiap detik yang berlalu, akan dipertanggungjawabkan.
  visi:
    title: Visi
    icon: hands-holding-child
    comment: Menjadi pesantren pilihan yang unggul dalam mendidik generasi yang beradab,
      berilmu, dan berdikari.
  misi:
    title: Misi
    item:
      id: 2
      icon: house-chimney-user
      comment: Menjadi rumah yang nyaman bagi penghafal Al-Qur'an dan penuntut ilmu
        syar'i.
