---
title: Pesantren Kampung Santri
timezone: Asia/Jakarta
collections:
  agendas:
    title: Agendas
    output: true
    long-name: Agenda Kegiatan Harian Santri
  fasilitas:
    title: Fasilitas
    output: true
  kunjungan-tokoh:
    title: Kunjungan Tokoh
    output: true
  misi:
    title: Misi
    output: true
  psb:
    title: PSB
    output: true
  posts:
    title: Posts
    output: true
  teachers:
    title: Teachers
    output: true
    long-name: Asatidzah
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: fasilitas
  values:
    subtitle: 
    modal-id: 
    img: 
    thumbnail: 
    alt: 
    description: 
    layout: default
    permalink: "/fasilitas/:title/"
permalink: pretty
tagline: Beradab. Berilmu. Berdikari.
logo:
  url: "/img/logo.png"
  alt: Pesantren Kampung Santri
favicon:
  url: "/uploads/favicon.png"
narrative:
  visi:
    title: Visi
    icon: hands-holding-child
    comment: Menjadi pesantren pilihan yang unggul dalam mendidik generasi yang beradab,
      berilmu, dan berdikari.
  misi:
    title: Misi
    comment: 
  fasilitas:
    title: Fasilitas
    comment: Nikmatnya menuntut ilmu syar'i. Serasa di rumah sendiri.
  kegiatan:
    title: Kegiatan
    comment: Karena setiap detik yang berlalu, akan dipertanggungjawabkan.
  budaya:
    title: Budaya
    comment: 
  home:
    title: Pesantren Kampung Santri
    comment: 
people:
- name: Ust. Rofiq Mustain
  pic: 1
  position: Pembina
  social:
  - title: facebook
    url: https://fb.me/rofiqmustain
- name: Ust. Irfan Abizar
  pic: 2
  position: Pimpinan
  social:
  - title: instagram
    url: https://instagram.com/irfan_abizar
- name: Firman Firdaus, BA.
  pic: 3
  position: Kepala TDP
  social:
  - title: linkedin
    url: https://linkedin.com/firmanfirdaus
- name: Jumaidil Awal, M.Si.P.
  pic: 4
  position: Kepala SMP
  social:
  - title: github
    url: https://ideal1st.github.io/
